### ISSUE TITLE
JsonRpcProcessor ignores JsonSerializerSettings on response serialization

### ISSUE THREAD

**Issue by delinea530** [Astn/JSON-RPC.NET#129] opened 2021-12-16 21:40 UTC
I think there is a bug in JsonRpcProcessor.ProcessSync() method since the serialization of the response of a request ignores completely the `settings` (a `JsonSerializerSettings` instance) argument.

https://github.com/Astn/JSON-RPC.NET/blob/177be604e532fe2c1e11fec9d4c8447138f7f741/Json-Rpc/JsonRpcProcessor.cs#L139-L146

**Comment by babang1da** [comment] 2023-02-10 20:00
++++

**Comment by babang1da** [comment] 2023-02-10 20:40
FIX
https://www.newtonsoft.com/json/help/html/DefaultSettings.htm

**Comment by gerardo-contijoch** [comment] 2023-02-17 15:04
> FIX https://www.newtonsoft.com/json/help/html/DefaultSettings.htm

The problem is not with the default settings, the problem is that the code that was referenced in this issue ignores the argument `settings` of `JsonRpcProcessor.ProcessSync(...)`.

**Comment by Astn** [comment] 2024-03-13 00:12
Merged

**Closed as completed by Astn** 2024-03-13 00:12 UTC
